import { NextResponse } from "next/server";
import { GoogleGenerativeAI } from "@google/generative-ai";
import { REPORT_SYSTEM_PROMPT } from "@/data/medical-prompts";

export async function POST(request: Request) {
  try {
    const body: unknown = await request.json();
    if (typeof body !== "object" || body === null || !("entities" in body)) {
      return NextResponse.json({ error: "Send { entities, language, transcript }" }, { status: 400 });
    }

    const { entities, language, transcript } = body as { entities: Record<string, unknown>; language?: string; transcript?: string };
    const apiKey = process.env.GOOGLE_GEMINI_API_KEY;

    if (!apiKey) {
      const now = new Date().toLocaleDateString("en-IN", { year: "numeric", month: "long", day: "numeric" });
      return NextResponse.json({
        report: `# Clinical Report\n**Date:** ${now}\n**Language:** ${language ?? "English"}\n\n## Chief Complaints\n- Fever for 3 days (moderate)\n- Headache (mild)\n- Body pain (moderate)\n\n## Vitals\n| Parameter | Value |\n|-----------|-------|\n| BP | 130/85 mmHg |\n\n## Diagnosis\n- Viral Pyrexia (R50.9)\n\n## Medications\n| Drug | Dosage | Frequency | Duration |\n|------|--------|-----------|----------|\n| Paracetamol | 500mg | Twice daily | 5 days |\n\n## Follow-Up\n- Review in 1 week\n\n---\n*Generated by VoiceMed AI (demo mode)*`,
        demo: true,
      });
    }

    const genAI = new GoogleGenerativeAI(apiKey);
    const model = genAI.getGenerativeModel({ model: "gemini-2.0-flash" });

    const chat = model.startChat({
      history: [
        { role: "user", parts: [{ text: REPORT_SYSTEM_PROMPT }] },
        { role: "model", parts: [{ text: "Ready to generate medical reports. Send me the extracted entities." }] },
      ],
    });

    const prompt = `Language: ${language ?? "English"}\nTranscript: "${transcript ?? ""}"\n\nExtracted Entities:\n${JSON.stringify(entities, null, 2)}`;
    const result = await chat.sendMessage(prompt);

    return NextResponse.json({ report: result.response.text(), demo: false });
  } catch (err) {
    const msg = err instanceof Error ? err.message : "Report generation failed";
    console.error("[report]", msg);
    return NextResponse.json({ error: msg }, { status: 500 });
  }
}
